import type { DealAnalysis } from "../../src/lib/types/analysis"

export const vreyAnalysis: DealAnalysis = {
  id: "analysis-2",
  dealId: "deal-2",
  status: "completed",
  createdAt: "2025-07-01T14:00:00Z",
  executiveSummary: {
    companyName: "VREY",
    stage: "Pre-seed",
    sector: "CleanTech / Renewable Energy Infrastructure",
    raising: "EUR 500K",
    geography: "Netherlands / Germany",
    mrr: "Pre-revenue (project-based)",
    verdict: "Explore",
    confidence: "Medium",
    overallScore: 58,
    scorecard: [
      { domain: "Team", score: 72, verdict: "Strong", keyFinding: "Experienced founding team with deep energy sector expertise. CEO has 15+ years in renewable energy project development.", dataCompleteness: 75 },
      { domain: "Market", score: 65, verdict: "Moderate", keyFinding: "Large and growing renewable energy market with strong EU regulatory tailwinds. TAM validated at EUR 50B+ in European energy infrastructure.", dataCompleteness: 70 },
      { domain: "Product", score: 55, verdict: "Moderate", keyFinding: "Containerized battery storage solution with proven technology. Unique modular approach enables faster deployment than traditional installations.", dataCompleteness: 60 },
      { domain: "Traction", score: 42, verdict: "Moderate", keyFinding: "2 completed pilot projects, 5 LOIs from municipal energy providers. Early revenue from project fees.", dataCompleteness: 50 },
      { domain: "Finance", score: 48, verdict: "Moderate", keyFinding: "Raising EUR 500K at EUR 3M pre-money. Capital-intensive business model requires careful cash management.", dataCompleteness: 55 },
    ],
    thesis: "VREY operates at the intersection of renewable energy infrastructure and distributed storage — a market with strong structural tailwinds driven by EU Green Deal mandates, rising energy costs, and grid decentralization. The founding team brings genuine domain expertise in energy project development, and the containerized battery storage approach offers faster deployment timelines than traditional installations. However, the capital-intensive nature of energy infrastructure creates significant scaling challenges at pre-seed, and unit economics remain unproven at scale.",
    strengths: [
      { id: 1, severity: "Info", text: "Experienced founding team with 15+ years combined energy sector expertise and existing relationships with municipal energy providers." },
      { id: 2, severity: "Info", text: "Strong regulatory tailwinds: EU Green Deal mandates EUR 300B+ in clean energy investment by 2030, directly driving demand for distributed storage solutions." },
      { id: 3, severity: "Info", text: "Modular containerized approach reduces deployment time from 6-12 months to 6-8 weeks, creating a meaningful speed advantage vs traditional installations." },
      { id: 4, severity: "Warning", text: "Early customer validation with 2 completed pilots and 5 LOIs, though revenue scale is minimal and unit economics are unproven." },
    ],
    risks: [
      { id: 1, severity: "Warning", text: "Capital-intensive business model: Each container unit costs EUR 150-200K, requiring significant working capital that EUR 500K raise may not adequately cover for scaling beyond 3-5 units." },
      { id: 2, severity: "Warning", text: "Regulatory dependency: Business model relies heavily on EU energy subsidies and feed-in tariffs, which could change with political cycles." },
      { id: 3, severity: "Info", text: "Hardware margins are thin (estimated 15-25%) compared to SaaS. Long-term defensibility depends on software/services layer that is still in development." },
    ],
    recommendedNextSteps: [
      "Schedule a deep-dive call with the founding team to understand unit economics per container deployment and path to positive contribution margin.",
      "Request detailed financial projections: capital requirements for next 24 months, break-even timeline, and Series A milestone plan.",
      "Conduct reference calls with the 2 pilot customers and validate LOI conversion likelihood with the 5 pipeline prospects.",
    ],
    dataCompleteness: 62,
  },
  team: {
    score: 72,
    verdict: "Strong",
    dataCompleteness: 75,
    founders: [
      {
        name: "Marcus Weber",
        role: "CEO & Co-Founder",
        background: "15+ years in renewable energy project development. Previously VP at Vattenfall, led EUR 200M wind farm portfolio. MSc Energy Engineering, TU Delft.",
        strength: "Deep domain expertise, established utility relationships, proven track record in energy project execution.",
        keyConcern: "First-time startup founder — transition from corporate to startup execution is unproven.",
        linkedinUrl: "https://linkedin.com/in/marcusweber",
      },
      {
        name: "Anna Visser",
        role: "CTO & Co-Founder",
        background: "10 years in battery technology R&D. PhD in Electrochemistry, University of Twente. 3 patents in battery management systems.",
        strength: "Strong technical foundation in core technology. Patent portfolio adds IP defensibility.",
        keyConcern: "R&D background — ability to ship production-ready hardware at scale is untested.",
        linkedinUrl: "https://linkedin.com/in/annavisser",
      },
    ],
    founderMarketFit: "Strong founder-market fit. Marcus brings deep industry relationships and project development experience from Vattenfall, while Anna brings core technical expertise in battery management systems. The combination of commercial domain expertise + technical depth is well-suited for energy infrastructure.",
    teamDynamics: "Complementary skill sets (commercial + technical). Have worked together for 2 years on VREY. Key gap: no dedicated sales/BD hire yet — Marcus is handling both CEO and sales functions, which will become a bottleneck at scale.",
    redFlags: [
      { id: 1, severity: "Warning", text: "First-time startup founders — both come from large corporate/academic backgrounds. Startup execution speed and scrappiness is unproven." },
      { id: 2, severity: "Info", text: "No dedicated sales hire yet. Marcus is handling CEO + BD, which limits pipeline capacity." },
    ],
  },
  market: {
    score: 65,
    verdict: "Moderate",
    dataCompleteness: 70,
    marketSize: [
      { metric: "TAM", founderClaim: "EUR 80B", validatedEstimate: "EUR 50-70B (European energy storage market 2030)", variance: "Founder claim slightly aggressive but directionally correct", assessment: "Large market with strong structural growth drivers" },
      { metric: "SAM", founderClaim: "EUR 5B", validatedEstimate: "EUR 3-5B (distributed/containerized storage in NL/DACH)", variance: "Reasonable", assessment: "Well-defined addressable segment" },
      { metric: "SOM", founderClaim: "EUR 50M (Y5)", validatedEstimate: "EUR 20-40M (realistic for pre-seed with EUR 500K)", variance: "Founder claim slightly optimistic", assessment: "Achievable but requires strong execution and follow-on capital" },
    ],
    marketDynamics: "European energy storage market growing at 35%+ CAGR driven by EU Green Deal mandates, rising energy costs, grid instability, and increasing renewable penetration requiring storage solutions. The Netherlands and Germany are leading markets due to dense grid infrastructure and aggressive decarbonization targets.",
    whyNow: "Three converging forces: (1) Battery costs have fallen 90% in the past decade, making distributed storage economically viable; (2) EU Green Deal mandates EUR 300B+ in clean energy by 2030; (3) Grid instability from renewable intermittency creates urgent demand for local storage. The timing window is strong.",
    whyNowScore: "Strong",
    competitors: [
      { name: "Fluence (Siemens/AES)", threatLevel: "High", differentiation: "VREY targets smaller, distributed deployments vs Fluence's utility-scale focus.", funding: "$936M raised" },
      { name: "Enphase Energy", threatLevel: "Medium", differentiation: "Enphase focuses on residential; VREY targets commercial/municipal.", funding: "Public ($4B+ market cap)" },
      { name: "Sonnen (Shell)", threatLevel: "Medium", differentiation: "Sonnen is residential-focused. VREY's containerized approach targets a different deployment profile.", funding: "Acquired by Shell" },
      { name: "Local installers", threatLevel: "Low", differentiation: "Fragmented market of local solar/storage installers. VREY's modular approach offers faster deployment.", funding: "N/A" },
    ],
    redFlags: [
      { id: 1, severity: "Warning", text: "Large incumbents (Fluence, Enphase, Shell/Sonnen) are well-funded and could move into distributed/containerized segment." },
      { id: 2, severity: "Info", text: "Market sizing relies on EU regulatory assumptions that could shift with political changes." },
    ],
  },
  product: {
    score: 55,
    verdict: "Moderate",
    dataCompleteness: 60,
    problemType: "Painkiller",
    painScore: "7/10",
    currentSolutions: "Municipal energy providers currently use utility-scale battery installations (12+ month deployment) or diesel generators (expensive, dirty). No good modular, rapidly-deployable solution exists for the 500kWh-2MWh segment.",
    evidenceOfPain: "2 completed pilot deployments with positive feedback. 5 LOIs from municipal energy providers indicate genuine demand. Rising energy costs and grid instability create urgent need.",
    solutionComparison: [
      { metric: "Deployment Time", value: "6-8 weeks", benchmark: "6-12 months (traditional)", status: "check", statusNote: "4-6x faster" },
      { metric: "Unit Cost", value: "EUR 150-200K per container", benchmark: "EUR 300-500K (traditional)", status: "check", statusNote: "50% lower" },
      { metric: "Scalability", value: "Modular (add containers)", benchmark: "Fixed (rebuild)", status: "check", statusNote: "Key advantage" },
      { metric: "Software Layer", value: "In development", benchmark: "Mature (incumbents)", status: "warning", statusNote: "Gap to close" },
    ],
    pmfStatus: "Early Signals",
    pmfDetails: "2 completed pilot projects with municipal energy providers, 5 LOIs in pipeline. Customers cite deployment speed and modular design as primary value drivers. Repeat interest from pilot customers suggests genuine pull.",
    moat: [
      { type: "Network Effects", present: false, strength: 1, evidence: "Potential for data network effects as more containers deployed, but too early." },
      { type: "Proprietary Data", present: true, strength: 4, evidence: "Pilot deployment data on battery performance in NL/DACH climate conditions. Growing with each deployment." },
      { type: "Switching Costs", present: true, strength: 5, evidence: "Hardware lock-in + service contracts create moderate switching costs once deployed." },
      { type: "Technology/IP", present: true, strength: 6, evidence: "3 patents on battery management systems. Proprietary containerization design. CTO's PhD research underpins core technology." },
    ],
    redFlags: [
      { id: 1, severity: "Warning", text: "Software layer is still in development — the long-term margin play depends on software/services, not hardware." },
      { id: 2, severity: "Info", text: "Hardware product requires manufacturing partnerships and supply chain management — different competency from software startups." },
    ],
  },
  traction: {
    score: 42,
    verdict: "Moderate",
    dataCompleteness: 50,
    revenueMetrics: [
      { metric: "Revenue (LTM)", value: "EUR 85K", benchmark: "Pre-seed: EUR 0-100K typical", status: "check", statusNote: "On track" },
      { metric: "Pipeline (LOIs)", value: "EUR 750K-1M (5 LOIs)", benchmark: "3-5x current revenue", status: "check", statusNote: "Healthy pipeline" },
      { metric: "Growth", value: "N/A (project-based)", benchmark: "N/A", status: "warning", statusNote: "Too early for growth rate" },
    ],
    unitEconomics: [
      { metric: "Gross Margin per Unit", value: "~20% (estimated)", benchmark: ">40% (SaaS)", status: "warning", statusNote: "Hardware margins are thin" },
      { metric: "Payback Period", value: "~18 months per unit", benchmark: "<18 months", status: "warning", statusNote: "Borderline" },
      { metric: "CAC", value: "Low (founder-led, direct sales)", benchmark: "Varies", status: "check", statusNote: "Efficient at current scale" },
    ],
    retention: [
      { metric: "Repeat Interest", value: "Both pilot customers exploring additional units", status: "check" },
      { metric: "Service Contract Renewal", value: "100% (2/2 pilots)", status: "check" },
      { metric: "Churn", value: "0% (too early, small sample)", status: "warning" },
    ],
    redFlags: [
      { id: 1, severity: "Warning", text: "Revenue is project-based, not recurring. Path to recurring revenue depends on software/services layer that is in development." },
      { id: 2, severity: "Info", text: "Small sample size (2 pilots, 5 LOIs) — too early to draw strong conclusions on unit economics or retention." },
    ],
  },
  finance: {
    score: 48,
    verdict: "Moderate",
    dataCompleteness: 55,
    financialHealth: [
      { metric: "Cash Position", value: "EUR 45K (founder-funded)", status: "warning", statusNote: "Limited runway" },
      { metric: "Monthly Burn", value: "~EUR 15K", status: "check", statusNote: "Lean for hardware startup" },
      { metric: "Runway", value: "~3 months at current burn", status: "critical", statusNote: "Urgent need for funding" },
      { metric: "Burn Multiple", value: "N/A (project-based revenue)", status: "warning" },
    ],
    capitalEfficiency: "Bootstrapped to EUR 85K revenue and 2 deployed pilot units on founder capital only. Strong capital efficiency signal — founders have demonstrated ability to execute with minimal resources. However, hardware scaling will require significantly more capital.",
    investorSignals: "No institutional investors yet. Founders have self-funded to date. EUR 500K raise at EUR 3M pre-money valuation. One angel investor has committed EUR 50K.",
    valuation: [
      { method: "Conservative", impliedValue: "EUR 2M pre-money", basis: "European pre-seed hardware startup with early revenue: EUR 1.5-2.5M typical" },
      { method: "Moderate", impliedValue: "EUR 3M pre-money (asking)", basis: "Pre-seed with pilots, LOIs, and IP: EUR 2.5-4M reasonable for NL" },
      { method: "Aggressive", impliedValue: "EUR 5M pre-money", basis: "Strong team + IP + CleanTech premium: could justify EUR 4-6M in current market" },
    ],
    dealTerms: "SAFE note, EUR 500K raise, EUR 3M valuation cap. Pro-rata rights offered. Founders retain 80% post-round (pre-ESOP). 10% ESOP planned.",
    redFlags: [
      { id: 1, severity: "Warning", text: "EUR 500K may be insufficient for hardware scaling — each container unit costs EUR 150-200K, limiting deployment to 2-3 additional units." },
      { id: 2, severity: "Info", text: "Capital-intensive model will require follow-on funding within 12-18 months. Series A readiness depends on proving unit economics at scale." },
    ],
  },
  exitPotential: {
    score: 60,
    verdict: "Moderate",
    dataCompleteness: 55,
    comparableExits: [
      { metric: "Sonnen (acquired by Shell)", value: "~EUR 500M", benchmark: "Residential battery storage", status: "check" },
      { metric: "Fluence Energy (IPO)", value: "$1.5B+ valuation", benchmark: "Utility-scale storage", status: "check" },
      { metric: "Stem Inc (SPAC)", value: "$1.35B valuation", benchmark: "AI-driven energy storage", status: "check" },
    ],
    exitRange: "Realistic exit range: EUR 50-200M (5-7 year horizon). Higher end requires successful transition to software/services model. Energy infrastructure exits tend to be strategic acquisitions by utilities or oil majors diversifying into clean energy.",
    exitTimeline: "5-7 years to meaningful exit. Requires: prove unit economics (Year 1-2), scale to EUR 5-10M revenue (Year 2-4), build software layer (Year 3-5), strategic acquisition or Series C+ (Year 5-7).",
    acquirerLandscape: "Shell (already acquired Sonnen), Vattenfall, Engie, E.ON, Siemens Energy, and PE firms focused on energy transition (Brookfield, Macquarie). Strong strategic interest in distributed storage acquisitions.",
    redFlags: [
      { id: 1, severity: "Info", text: "Hardware-focused companies typically exit at lower multiples than software (2-4x revenue vs 10-20x). Software layer is critical for higher exit valuation." },
    ],
  },
  fundFit: {
    score: 78,
    verdict: "Strong",
    dataCompleteness: 85,
    criteria: [
      { criterion: "Stage", fundProfile: "Seed / Series A", deal: "Pre-seed", match: false },
      { criterion: "Sector", fundProfile: "SaaS, CleanTech", deal: "CleanTech / Energy Infrastructure", match: true },
      { criterion: "Geography", fundProfile: "Europe, Netherlands", deal: "Netherlands / Germany", match: true },
      { criterion: "Ticket Size", fundProfile: "EUR 250K - 2M", deal: "EUR 500K raise (EUR 100-250K ticket)", match: true },
    ],
    thesisAlignment: 72,
    portfolioConflict: "No direct portfolio conflicts. Complementary to existing CleanTech investments in solar and EV charging.",
  },
  missingInfo: {
    sections: [
      {
        section: "Traction",
        items: ["Detailed unit economics per container deployment", "Pipeline conversion rates", "Customer acquisition cost breakdown"],
        impact: "Cannot fully validate path to profitability",
        followUpQuestions: ["What is the fully-loaded cost per container deployment including installation?", "What is your LOI-to-contract conversion rate historically?"],
      },
      {
        section: "Finance",
        items: ["24-month financial projections", "Series A milestone plan", "Detailed use of funds for EUR 500K"],
        impact: "Cannot assess capital sufficiency for next phase",
        followUpQuestions: ["How will you allocate the EUR 500K?", "What milestones do you need to hit for Series A?", "What is your projected burn rate post-raise?"],
      },
      {
        section: "Product",
        items: ["Software platform roadmap and timeline", "Manufacturing partner details", "Supply chain risk assessment"],
        impact: "Cannot assess long-term margin structure or scaling risk",
        followUpQuestions: ["When will the software platform be ready?", "Who manufactures the container units?", "What is your battery cell supply chain?"],
      },
    ],
    overallCompleteness: 62,
  },
}
