import { NextResponse } from "next/server"
import { generateExecutiveSummaryDocx } from "@/lib/generate-docx"
import { mockDeals } from "@/lib/mock-data/deals"

export async function POST(request: Request) {
  try {
    const { dealId, recipientEmail } = await request.json()

    const deal = mockDeals.find((d) => d.id === dealId)
    if (!deal?.analysis) {
      return NextResponse.json({ error: "Deal or analysis not found" }, { status: 404 })
    }

    const es = deal.analysis.executiveSummary
    const buffer = await generateExecutiveSummaryDocx(es)
    const filename = `SAM_${deal.companyName.replace(/\s+/g, "_")}_Executive_Summary.docx`

    // Check if Resend API key is configured
    const resendKey = process.env.RESEND_API_KEY
    if (!resendKey) {
      // Fallback: return the doc as download if email not configured
      return NextResponse.json({
        success: false,
        message: "Email not configured (RESEND_API_KEY missing). Document generated but not sent.",
        fallbackDownload: true,
      })
    }

    const { Resend } = await import("resend")
    const resend = new Resend(resendKey)

    await resend.emails.send({
      from: "SAM <noreply@resend.dev>",
      to: recipientEmail,
      subject: `SAM Analysis: ${es.companyName} — ${es.verdict}`,
      html: `
        <div style="font-family: Calibri, sans-serif; max-width: 600px;">
          <h2 style="margin-bottom: 4px;">SAM — AI Investment Associate</h2>
          <p style="color: #666; margin-top: 0;">Executive Summary for ${es.companyName}</p>
          <hr style="border: 1px solid #eee;" />
          <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
            <tr>
              <td style="padding: 8px 0;"><strong>Verdict</strong></td>
              <td style="padding: 8px 0; color: ${es.verdict === "Strong Buy" ? "#2E7D32" : es.verdict === "Deny" ? "#C62828" : "#F57F17"}; font-weight: bold;">${es.verdict.toUpperCase()}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0;"><strong>Confidence</strong></td>
              <td style="padding: 8px 0;">${es.confidence}</td>
            </tr>
            <tr>
              <td style="padding: 8px 0;"><strong>Overall Score</strong></td>
              <td style="padding: 8px 0;">${es.overallScore}/100</td>
            </tr>
            <tr>
              <td style="padding: 8px 0;"><strong>Stage</strong></td>
              <td style="padding: 8px 0;">${es.stage}</td>
            </tr>
          </table>
          <p><strong>Thesis:</strong> ${es.thesis}</p>
          <p style="color: #888; font-size: 12px; margin-top: 24px;">Full analysis attached as Word document. Generated by SAM.</p>
        </div>
      `,
      attachments: [
        {
          filename,
          content: buffer.toString("base64"),
        },
      ],
    })

    return NextResponse.json({ success: true, message: `Email sent to ${recipientEmail}` })
  } catch (error) {
    console.error("Email export error:", error)
    return NextResponse.json({ error: "Failed to send email" }, { status: 500 })
  }
}
