import type { DealAnalysis } from "../types/analysis"

export const canaароAnalysis: DealAnalysis = {
  id: "analysis-1",
  dealId: "deal-1",
  status: "completed",
  createdAt: "2025-06-15T10:00:00Z",
  executiveSummary: {
    companyName: "Canaaro",
    stage: "Seed",
    sector: "GTM Productivity / Sales Enablement / RevOps SaaS",
    raising: "Not disclosed",
    geography: "Netherlands",
    mrr: "Not disclosed",
    verdict: "Deny",
    confidence: "Low",
    overallScore: 24,
    scorecard: [
      { domain: "Team", score: 28, verdict: "Weak", keyFinding: "Complete absence of verifiable founder backgrounds — no LinkedIn profiles, no digital footprint, no career history, no domain expertise evidence.", dataCompleteness: 15 },
      { domain: "Market", score: 38, verdict: "Weak", keyFinding: "The underlying GTM productivity market is large ($5B+ SAM) and growing fast (20%+ CAGR), but the competitive landscape is brutally crowded with well-capitalized incumbents.", dataCompleteness: 35 },
      { domain: "Product", score: 22, verdict: "Weak", keyFinding: "No product is described anywhere in the materials — no solution, no screenshots, no demo, no architecture, no technology approach.", dataCompleteness: 10 },
      { domain: "Traction", score: 12, verdict: "Weak", keyFinding: "Zero traction metrics of any kind — no revenue, no users, no pilots, no LOIs, no waitlist, no engagement data.", dataCompleteness: 5 },
      { domain: "Finance", score: 18, verdict: "Weak", keyFinding: "Complete financial blackout — no round size, no valuation, no burn rate, no runway, no cap table, no deal terms.", dataCompleteness: 5 },
    ],
    thesis: "Canaaro targets a legitimate and large problem — GTM team inefficiency — in a market growing at 20%+ CAGR with a $5-8B serviceable addressable market. However, the investment thesis cannot be constructed because the pitch materials consist of only two slides (a title page and a single problem statement), providing no information about the product, solution approach, team backgrounds, traction, business model, financials, or competitive differentiation.",
    strengths: [
      { id: 1, severity: "Info", text: "Large and growing addressable market: The GTM productivity / sales engagement market has a validated SAM of $5-8B, growing at 20-24% CAGR, driven by AI automation and rising GTM headcount costs." },
      { id: 2, severity: "Info", text: "Real and widely validated problem: GTM inefficiency is a genuine, quantified pain point experienced daily by sales and marketing teams globally." },
      { id: 3, severity: "Info", text: "Favorable cost structure potential: Netherlands-based founding team likely has a lower burn rate than US-based equivalents." },
    ],
    risks: [
      { id: 1, severity: "Critical", text: "Complete information vacuum across all domains: The pitch deck consists of only 2 slides with no product description, no team bios, no traction data, no financial information, no competitive positioning, and no business model." },
      { id: 2, severity: "Critical", text: "Hyper-competitive market with no articulated differentiation: The GTM tools space has attracted billions in venture capital (Outreach $489M, Gong $584M, Apollo $244M, Clay $62M+)." },
      { id: 3, severity: "Critical", text: "Unverifiable founders with no demonstrated domain expertise: Neither co-founder has any discoverable professional background, LinkedIn presence, or digital footprint." },
    ],
    recommendedNextSteps: [
      "PASS on the current submission. Inform founders that the materials provided are insufficient for institutional seed-stage evaluation.",
      "If founders re-engage with complete materials: Request LinkedIn profiles and conduct thorough background verification.",
      "If founders demonstrate a working product with early traction: Request a live product demo and access to pilot customer references.",
    ],
    dataCompleteness: 14,
  },
  team: {
    score: 28,
    verdict: "Weak",
    dataCompleteness: 15,
    founders: [
      {
        name: "Joost de Stigter",
        role: "Co-Founder (undefined)",
        background: "No educational background, career history, or professional track record could be identified.",
        strength: "Cannot be identified from available data.",
        keyConcern: "Complete absence of any verifiable professional or educational background.",
      },
      {
        name: "Sander Grau",
        role: "Co-Founder (undefined)",
        background: "No educational background, career history, or professional track record could be identified.",
        strength: "Cannot be identified from available data.",
        keyConcern: "Identical to co-founder — total information vacuum on credentials.",
      },
    ],
    founderMarketFit: "Founder-market fit is the single most important signal at seed stage, and it is entirely unassessable here. The GTM productivity space requires founders with deep, lived experience inside Go-to-Market organizations. There is zero evidence that either founder has any such experience.",
    teamDynamics: "Team dynamics are entirely unknown. We have no information on how long the co-founders have known each other, whether they have previously worked together, how responsibilities are divided, or whether either is technical.",
    redFlags: [
      { id: 1, severity: "Critical", text: "No LinkedIn URLs provided in pitch deck — highly unusual and suggests either weak profiles being deliberately omitted or a desire to avoid scrutiny." },
      { id: 2, severity: "Critical", text: "Google search returns zero meaningful results for either founder — no press mentions, no articles, no conference talks, no social presence." },
      { id: 3, severity: "Warning", text: "No role differentiation between co-founders — both listed as 'Co-Founder' with no further title. No evidence of technical capability." },
    ],
  },
  market: {
    score: 38,
    verdict: "Weak",
    dataCompleteness: 35,
    marketSize: [
      { metric: "TAM", founderClaim: "Not stated", validatedEstimate: "~$25-30B (Global Sales Technology / RevOps)", variance: "N/A", assessment: "Cannot assess — absence of any TAM claim is a red flag" },
      { metric: "SAM", founderClaim: "Not stated", validatedEstimate: "~$5-8B (GTM productivity / sales engagement)", variance: "N/A", assessment: "Market is large but Canaaro's specific segment is unclear" },
      { metric: "SOM", founderClaim: "Not stated", validatedEstimate: "~$10-50M (realistic Y5 for EU Seed entrant)", variance: "N/A", assessment: "Entirely speculative without product or GTM detail" },
    ],
    marketDynamics: "The GTM productivity / sales engagement market is estimated at ~$3.4B (2023) and projected to reach $12-15B by 2030, growing at 20-24% CAGR. Growth is driven by AI-enabled automation of repetitive GTM tasks, increasing complexity of multi-channel selling, and rising headcount costs.",
    whyNow: "No 'Why Now?' argument is articulated in the pitch deck — a major red flag. The most plausible timing catalyst is the explosion of generative AI / LLM capabilities (2023-2025), but this cuts both ways: AI enables new entrants but ALSO enables incumbents to rapidly add AI features.",
    whyNowScore: "Weak",
    competitors: [
      { name: "Outreach", threatLevel: "Very High", differentiation: "No differentiation articulated. Canaaro cites Outreach's own research as its problem validation.", funding: "$489M raised" },
      { name: "Apollo.io", threatLevel: "High", differentiation: "No differentiation articulated. Apollo offers AI-native prospecting at aggressive price points.", funding: "$244M raised" },
      { name: "Clay", threatLevel: "High", differentiation: "No differentiation articulated. Clay is rapidly gaining traction as AI-native GTM workflow platform.", funding: "$62M+ raised" },
      { name: "HubSpot Sales Hub", threatLevel: "Very High", differentiation: "No differentiation articulated. HubSpot has massive distribution and is integrating AI aggressively.", funding: "$36B+ market cap" },
    ],
    redFlags: [
      { id: 1, severity: "Critical", text: "Hyper-competitive market with massive incumbents: Outreach ($489M), Salesloft (~$2.4B acquisition), HubSpot ($36B), Gong ($584M), Apollo ($244M)." },
      { id: 2, severity: "Critical", text: "No TAM/SAM/SOM, no 'Why Now?', and problem statement sourced from a dominant competitor (Outreach)." },
    ],
  },
  product: {
    score: 22,
    verdict: "Weak",
    dataCompleteness: 10,
    problemType: "Vitamin (borderline Nice-to-Have)",
    painScore: "4/10",
    currentSolutions: "Customers currently address GTM inefficiency through a massive ecosystem: Outreach, Salesloft, Gong, Apollo, Clay, HubSpot, Salesforce, plus dozens of point solutions.",
    evidenceOfPain: "The 64% wasted GTM time statistic is directionally accurate and widely cited, but it is the most generic problem statement in B2B SaaS. No proprietary customer discovery data is presented.",
    solutionComparison: [
      { metric: "Labor Cost", value: "Not disclosed", benchmark: "Not disclosed", status: "gap" },
      { metric: "Speed", value: "Not disclosed", benchmark: "Not disclosed", status: "gap" },
      { metric: "Flexibility", value: "Not disclosed", benchmark: "Not disclosed", status: "gap" },
      { metric: "Coverage", value: "Not disclosed", benchmark: "Not disclosed", status: "gap" },
    ],
    pmfStatus: "No PMF Evidence / Pre-Product",
    pmfDetails: "Zero product-market fit signals of any kind. No organic growth, no customer pull, no engagement data, no retention data, no NPS, no testimonials, no case studies, no pilot results.",
    moat: [
      { type: "Network Effects", present: false, strength: 0, evidence: "No evidence of multi-user dynamics." },
      { type: "Proprietary Data", present: false, strength: 0, evidence: "No indication of unique data collection." },
      { type: "Switching Costs", present: false, strength: 0, evidence: "No product integration described." },
      { type: "Technology/IP", present: false, strength: 0, evidence: "No technology described. No patents or proprietary AI/ML models." },
    ],
    redFlags: [
      { id: 1, severity: "Critical", text: "No solution described — the most fundamental requirement of a product analysis cannot be met." },
      { id: 2, severity: "Critical", text: "Product easily replicable by incumbents — any feature can be replicated by Outreach, Apollo, Clay, or HubSpot within 6-12 months." },
    ],
  },
  traction: {
    score: 12,
    verdict: "Weak",
    dataCompleteness: 5,
    revenueMetrics: [
      { metric: "ARR", value: "Not disclosed", benchmark: "Seed: $5K-$50K MRR", status: "gap", statusNote: "Critical data gap" },
      { metric: "Historical Revenue", value: "Not disclosed", benchmark: "N/A", status: "gap", statusNote: "Critical data gap" },
      { metric: "Growth Trajectory", value: "Cannot assess", benchmark: "N/A", status: "gap", statusNote: "No growth data" },
    ],
    unitEconomics: [
      { metric: "LTV:CAC", value: "Not disclosed", benchmark: ">3:1", status: "gap" },
      { metric: "Payback Period", value: "Not disclosed", benchmark: "<18 months", status: "gap" },
      { metric: "Gross Margin", value: "Not disclosed", benchmark: ">70%", status: "gap" },
      { metric: "NRR", value: "Not disclosed", benchmark: ">100%", status: "gap" },
      { metric: "CAC", value: "Not disclosed", benchmark: "Varies", status: "gap" },
    ],
    retention: [
      { metric: "DAU/MAU", value: "Not disclosed", status: "gap" },
      { metric: "Cohort Retention", value: "Not disclosed", status: "gap" },
      { metric: "Logo Churn", value: "Not disclosed", status: "gap" },
      { metric: "Revenue Churn", value: "Not disclosed", status: "gap" },
    ],
    redFlags: [
      { id: 1, severity: "Critical", text: "Zero traction metrics of any kind — not a single company-specific quantitative metric was presented." },
      { id: 2, severity: "Critical", text: "No product detail — we do not know what the product actually does, whether it exists, or what development stage it is in." },
      { id: 3, severity: "Warning", text: "Highly competitive market with no differentiation — the only data point cited is from Outreach, a dominant competitor." },
    ],
  },
  finance: {
    score: 18,
    verdict: "Weak",
    dataCompleteness: 5,
    financialHealth: [
      { metric: "Cash Position", value: "Not disclosed", status: "gap", statusNote: "Critical data gap" },
      { metric: "Monthly Burn", value: "Not disclosed", status: "gap", statusNote: "Critical data gap" },
      { metric: "Runway", value: "Not disclosed", status: "gap", statusNote: "Critical data gap" },
      { metric: "Burn Multiple", value: "Not disclosed", status: "gap", statusNote: "Cannot calculate" },
    ],
    capitalEfficiency: "Capital efficiency cannot be assessed. No prior investors, angels, accelerators, or grants are mentioned. No product screenshots, demos, metrics, or customer logos provided.",
    investorSignals: "No investors disclosed. Complete absence of investor history. No angels, VCs, accelerators, grants, or strategic backers mentioned.",
    valuation: [
      { method: "Conservative", impliedValue: "Cannot compute", basis: "European seed-stage GTM SaaS with no traction: EUR 2-4M pre-money typical" },
      { method: "Moderate", impliedValue: "Cannot compute", basis: "European seed with some traction (EUR 50K-200K ARR): EUR 5-10M typical" },
      { method: "Aggressive", impliedValue: "Cannot compute", basis: "US-comparable seed with strong traction and team: $8-15M. None evidenced here." },
    ],
    dealTerms: "No deal terms of any kind are disclosed. No round size, no valuation, no instrument type, no liquidation preference, no board composition, no pro-rata rights.",
    redFlags: [
      { id: 1, severity: "Critical", text: "Complete financial data blackout: Not a single financial metric is disclosed." },
      { id: 2, severity: "Critical", text: "No investor history or validation signals: No prior investors, angels, accelerators, or grants mentioned." },
      { id: 3, severity: "Warning", text: "No use of funds or milestone framework: Cannot assess round sizing or Series A readiness path." },
    ],
  },
  exitPotential: {
    score: 20,
    verdict: "Weak",
    dataCompleteness: 30,
    comparableExits: [
      { metric: "Salesloft (Vista Equity)", value: "~$2.3B acquisition", benchmark: "Sales engagement", status: "check" },
      { metric: "Outreach", value: "IPO-track, ~$4.4B valuation", benchmark: "Sales engagement", status: "check" },
      { metric: "Gong", value: "$584M raised, $7.2B peak valuation", benchmark: "Conversation intelligence", status: "check" },
    ],
    exitRange: "The GTM tools space has produced multiple $1B+ outcomes, suggesting a strong exit environment for successful companies. However, without any product or traction, exit potential is entirely speculative for Canaaro.",
    exitTimeline: "Typical Seed-to-exit timeline in GTM SaaS: 7-10 years. Given pre-product status, the timeline is likely longer.",
    acquirerLandscape: "Potential acquirers include Salesforce, HubSpot, Microsoft, Oracle, and private equity firms (Vista Equity, Thoma Bravo). Strategic acquirers actively consolidating in this space.",
    redFlags: [
      { id: 1, severity: "Warning", text: "No product or traction makes exit potential entirely speculative. Market exits validate sector, not this company." },
    ],
  },
  fundFit: {
    score: 45,
    verdict: "Moderate",
    dataCompleteness: 60,
    criteria: [
      { criterion: "Stage", fundProfile: "Seed / Series A", deal: "Seed", match: true },
      { criterion: "Sector", fundProfile: "SaaS, Fintech", deal: "GTM SaaS", match: true },
      { criterion: "Geography", fundProfile: "Europe, Netherlands", deal: "Netherlands", match: true },
      { criterion: "Ticket Size", fundProfile: "EUR 250K - 2M", deal: "Not disclosed", match: false },
    ],
    thesisAlignment: 35,
    portfolioConflict: "No portfolio conflicts identified.",
  },
  missingInfo: {
    sections: [
      {
        section: "Team",
        items: ["LinkedIn profiles for both founders", "Career history and professional background", "Role differentiation (CEO/CTO/CPO)", "Technical capability evidence", "Prior startup or operator experience"],
        impact: "Cannot assess founder-market fit, which is the #1 signal at seed stage",
        followUpQuestions: ["Can you share your LinkedIn profiles?", "What is your background in GTM/SaaS specifically?", "Who is the technical co-founder?"],
      },
      {
        section: "Product",
        items: ["Product description or demo", "Solution architecture", "Technology approach", "Screenshots or mockups", "MVP status"],
        impact: "Cannot evaluate product viability or differentiation",
        followUpQuestions: ["What does Canaaro actually build/do?", "Do you have a working MVP or prototype?", "How is your approach different from Outreach/Clay?"],
      },
      {
        section: "Traction",
        items: ["Revenue or user metrics", "Pilot customers or LOIs", "Waitlist or design partners", "Engagement data", "Customer discovery insights"],
        impact: "Zero basis for investment conviction without any traction signal",
        followUpQuestions: ["Do you have any paying customers or pilots?", "Have you conducted customer interviews? What did you learn?", "Is there a waitlist?"],
      },
      {
        section: "Finance",
        items: ["Round size and valuation", "Burn rate and runway", "Cap table composition", "Use of funds breakdown", "Prior fundraising history"],
        impact: "Institutional investment evaluation is impossible without financial data",
        followUpQuestions: ["How much are you raising and at what valuation?", "What is your current burn rate?", "Have you received any prior investment?"],
      },
      {
        section: "Market",
        items: ["TAM/SAM/SOM sizing", "Why Now thesis", "Competitive differentiation strategy", "Go-to-market plan"],
        impact: "Cannot assess market positioning or right to win",
        followUpQuestions: ["How do you size your market?", "Why is now the right time for Canaaro specifically?", "What is your competitive wedge vs Outreach?"],
      },
    ],
    overallCompleteness: 14,
  },
}
